### PR TITLE
Fix example typos and style.

### PR DESCRIPTION
**Pull request by smortex**
- Use `do` / `end` instead of invalid `{` / `end`;
- Use the `dav` block parameter;
- Fix spacing.

### CODE REVIEW

**Comment by thomasfl** [comment]
Thanks for the pull request @smortex ! :-)

@devrandom Maybe you should add me as a collaborator one day, so I can merge pull requests?

**Comment by devrandom** [comment]
@thomasfl sorry I missed this message.  Added.

**Comment by bradgessler** [comment]
@thomasfl @devrandom lots of little issues to merge! Add me a a collaborator and I'll follow through at least on this request.

**Comment by thomasfl** [comment]
Miron @devrandom, can you add @bradgessler as a collaborator? I don't have access to the settings for this repo.

**Review by mrgordon — APPROVED** [review]

**Comment by mrgordon** [comment]
Please merge, wasted time figuring out why the example is wrong

**Comment by smortex** [comment]
Hello!

I just rebased these changes on top of master, in order to fix merge conflict.

**Comment by devrandom** [comment]
Thank you, sorry for the long delay.

**Pull request merged**
